/**
 * The node catalog, as the site reads it.
 *
 * The file behind this is generated by scripts/build-node-previews.mjs from
 * src/nodes/ — real node components, resolved through the framework. Pages
 * read it and never describe a node themselves, so the docs and the homepage
 * cannot drift from each other or from the toolkit.
 */
import generated from "./generated/node-catalog.json";

export type NodeStatus = "stable" | "no-helper" | "planned";
export type NodeCategory = "Structure" | "Text" | "Media" | "Data";

export interface NodeOption {
  name: string;
  type: string;
  required?: boolean;
  summary: string;
}

export interface PromptSpec {
  kind: string;
  text: string;
}

export interface NodeVariant {
  id: string;
  title: string;
  summary: string;
  /** Relative to src/nodes/ — the file the preview was built from. */
  sourceFile: string;
  previewUrl: string;
  /** The node this variant resolves to in a preview build. */
  resolved: Record<string, unknown>;
  /** Prompts a generation endpoint receives, or null for a static node. */
  prompts: PromptSpec[] | null;
}

export interface NodeType {
  id: string;
  title: string;
  kind: string;
  category: NodeCategory;
  status: NodeStatus;
  helpers: string[];
  summary: string;
  detail: string;
  children: string;
  resolves: string;
  /** Set where the shipped renderers do less than the node describes. */
  renderNote: string | null;
  options: NodeOption[];
  variants: NodeVariant[];
}

export const NODE_CATEGORIES = generated.categories as NodeCategory[];
export const NODE_TYPES = generated.types as NodeType[];

/** Types with a page of their own — everything the toolkit can actually build. */
export const SHIPPED_NODE_TYPES = NODE_TYPES.filter((type) => type.status !== "planned");

export const STATUS_LABELS: Record<NodeStatus, string> = {
  "stable": "Stable",
  "no-helper": "No helper yet",
  "planned": "Planned",
};

/**
 * Throws rather than returning undefined: a page naming a node type that left
 * the catalog is a broken page, and it should fail the build, not render empty.
 */
export function nodeType(id: string): NodeType {
  const found = NODE_TYPES.find((type) => type.id === id);

  if (!found) {
    throw new Error(
      `Unknown node type "${id}". Known types: ${NODE_TYPES.map((type) => type.id).join(", ")}.`,
    );
  }

  return found;
}

/** Where a node type's documentation lives. Planned types have no page yet. */
export function nodeTypeHref(type: NodeType): string | undefined {
  return type.status === "planned" ? undefined : `/docs/nodes/${type.id}/`;
}

export function byCategory(types: NodeType[] = NODE_TYPES) {
  return NODE_CATEGORIES.map((category) => ({
    category,
    types: types.filter((type) => type.category === category),
  })).filter((entry) => entry.types.length > 0);
}
