/**
 * The theme and component registry, as the site reads it.
 *
 * The file behind this is generated by scripts/build-registry.mjs from the
 * package's own catalog — real themes, real component sources, resolved
 * through the framework and rendered by the renderer the CLI ships. Pages read
 * it and describe nothing themselves, so `dxcl add slate-report` and the page
 * about Slate Report cannot disagree.
 *
 * Like the node catalog, the entries stay English in every language: a
 * translation of them could not be regenerated, so it would drift out of step
 * with the toolkit silently. The chrome around them is translated.
 */
import generated from "./generated/registry.json";

/**
 * How a theme sets its title and its section headings.
 *
 * Typed rather than left as a bag: every page that draws a specimen reads
 * fontSizePt and transform out of it, and a Record<string, unknown> makes each
 * of those an assertion at the call site instead of a fact here.
 */
export interface ThemeHeadingStyle {
  fontSizePt: number;
  weight: string;
  spacingBeforePt: number;
  spacingAfterPt: number;
  /** Hex without the hash, where the theme sets one apart from the palette. */
  color?: string;
  /** `uppercase` where the theme sets headings in capitals. */
  transform?: string;
}
export interface ThemePageEntry {
  id: string;
  title: string;
  summary: string;
  detail: string;
  category: string;
  tags: string[];
  /** Every font the theme asks for, in the order a reader meets them. */
  fonts: string[];
  /** The resolved style — what the install writes and the document carries. */
  style: {
    preset: string;
    page: {
      size: string;
      orientation: string;
      margins: { topMm: number; rightMm: number; bottomMm: number; leftMm: number };
    };
    typography: {
      bodyFont: string;
      headingFont: string;
      bodySizePt: number;
      bodyLineHeight: number;
      color: string;
    };
    palette?: { heading: string; accent: string; muted: string; rule: string; page: string };
    paragraph: { spacingAfterPt: number };
    title: ThemeHeadingStyle;
    sectionHeading: ThemeHeadingStyle;
  };
  /** A sample document set in this theme, rendered by the real renderer. */
  previewUrl: string;
}

export interface RegistryDataField {
  path: string;
  type: string;
  summary: string;
}

export interface RegistryFileEntry {
  /** Path inside the package's registry directory. */
  source: string;
  /** Where `dxcl add` puts it, relative to the document project. */
  target: string;
  /** The source itself — what would be copied in, shown rather than described. */
  code: string;
}

/**
 * One node a component resolved to — what a renderer or an engine is handed.
 *
 * The shape a built document carries, narrowed to the fields the pages read.
 * Every field past the first three is per-kind, so they are all optional here
 * rather than split into a union the pages would have to discriminate.
 */
export interface ResolvedNode {
  id: string;
  kind: string;
  /** `static` where it resolved locally, `dynamic` where an engine fills it. */
  mode?: string;
  text?: string;
  title?: string;
  path?: string;
  alt?: string;
  width?: number;
  height?: number;
  /** Which plot, on a `graph` node. */
  graphType?: string;
  /** Whether a `graph` stacks its series, and to a total or to a share. */
  stacked?: boolean | "percent";
  /** What a `graph` plots, which is what a miniature of it is drawn from. */
  data?: {
    categories?: string[];
    series?: Array<{ label?: string; values?: (number | null)[]; sizes?: (number | null)[] }>;
  };
  /** The block style a node asked its theme for, where it asked for one. */
  variant?: string;
  children?: ResolvedNode[];
}
export interface ComponentPageEntry {
  id: string;
  title: string;
  summary: string;
  detail: string;
  category: string;
  tags: string[];
  /** The component names the files export. */
  exports: string[];
  /** What it reads, so a reader knows what their data has to carry. */
  dataFields: RegistryDataField[];
  requires: string[];
  /** The theme it was drawn against, where there is one. */
  themeHint: string | null;
  files: RegistryFileEntry[];
  /** The data the preview was built against. */
  previewData: Record<string, unknown>;
  /** What it resolved to: the nodes a renderer or an engine is handed. */
  resolved: ResolvedNode[];
  previewUrl: string;
}

export const THEMES = generated.themes as ThemePageEntry[];
export const THEME_CATEGORIES = generated.themeCategories as string[];
export const COMPONENTS = generated.components as ComponentPageEntry[];
export const COMPONENT_CATEGORIES = generated.componentCategories as string[];

/**
 * Throws rather than returning undefined: a page naming something that left the
 * registry is a broken page, and it should fail the build rather than render
 * empty.
 */
export function themeEntry(id: string): ThemePageEntry {
  const found = THEMES.find((theme) => theme.id === id);

  if (!found) {
    throw new Error(
      `Unknown theme "${id}". Known: ${THEMES.map((theme) => theme.id).join(", ")}.`,
    );
  }

  return found;
}

export function componentEntry(id: string): ComponentPageEntry {
  const found = COMPONENTS.find((component) => component.id === id);

  if (!found) {
    throw new Error(
      `Unknown component "${id}". Known: ${COMPONENTS.map((entry) => entry.id).join(", ")}.`,
    );
  }

  return found;
}

/** Where a theme or component lives, canonically. Pass through `localizePath`. */
export function themeHref(id: string): string {
  return `/themes/${id}/`;
}

export function componentHref(id: string): string {
  return `/components/${id}/`;
}

/**
 * What a component is made of, as the browse page groups them.
 *
 * A second axis from `category`, and a different question. `category` says
 * *where* a component sits — an opening, a closing, something legal — which is
 * what you want when you are assembling a document top to bottom. This says
 * *what it is*, which is what you want when you are looking for a chart.
 */
export type ComponentFamily = "Graphs" | "Tables" | "Blocks" | "Paragraphs" | "Mixed";

/**
 * The families, in the order the page lists them: the ones that draw
 * something, then the ones that are words, then the ones that are both.
 */
export const COMPONENT_FAMILIES: readonly ComponentFamily[] = [
  "Graphs",
  "Tables",
  "Blocks",
  "Paragraphs",
  "Mixed",
];

/**
 * Which family a component belongs to, read out of what it resolved to.
 *
 * Derived rather than declared beside it in the catalog, for the reason the
 * rest of this file is derived: a field a person maintains is a field that
 * disagrees with the code the first time a component grows a chart. What a
 * component resolves to is what a renderer is handed, so it cannot be wrong
 * about itself.
 *
 * The order below is precedence, and the rule behind it is that a component is
 * named after the thing you came for. Almost every chart component is a chart
 * with a sentence beside it — that is the shape this registry recommends — and
 * filing those under "Mixed" because they also hold a paragraph would empty
 * the group somebody looking for a chart is actually browsing. A `section` is
 * skipped throughout: it is a container, not a thing on the page.
 */
export function familyOf(component: ComponentPageEntry): ComponentFamily {
  const kinds = new Set<string>();

  const walk = (nodes: readonly ResolvedNode[]) => {
    for (const node of nodes) {
      if (node.kind !== "section") kinds.add(node.kind);
      if (node.children) walk(node.children);
    }
  };

  walk(component.resolved);

  if (kinds.has("graph")) return "Graphs";
  if (kinds.has("table")) return "Tables";
  if (kinds.has("shape")) return "Blocks";

  // Paragraphs and nothing else. A signature block is paragraphs *and* a
  // picture, and neither of the two is the thing you came for, so it is mixed.
  return kinds.size === 1 && kinds.has("paragraph") ? "Paragraphs" : "Mixed";
}

/** The catalog grouped by family for the browse page, empty groups dropped. */
export function componentsByFamily(): {
  family: ComponentFamily;
  components: ComponentPageEntry[];
}[] {
  return COMPONENT_FAMILIES
    .map((family) => ({
      family,
      components: COMPONENTS.filter((component) => familyOf(component) === family),
    }))
    .filter((group) => group.components.length > 0);
}

/** The catalog grouped for a browse page, empty groups dropped. */
export function componentsByCategory(): { category: string; components: ComponentPageEntry[] }[] {
  return COMPONENT_CATEGORIES
    .map((category) => ({
      category,
      components: COMPONENTS.filter((component) => component.category === category),
    }))
    .filter((group) => group.components.length > 0);
}

export function themesByCategory(): { category: string; themes: ThemePageEntry[] }[] {
  return THEME_CATEGORIES
    .map((category) => ({
      category,
      themes: THEMES.filter((theme) => theme.category === category),
    }))
    .filter((group) => group.themes.length > 0);
}

/** The command that installs one, printed on every card and page. */
export function addCommand(id: string): string {
  return `npx dxcl add ${id}`;
}
