/**
 * The theme and component registry, as the site reads it.
 *
 * The file behind this is generated by scripts/build-registry.mjs from the
 * package's own catalog — real themes, real component sources, resolved
 * through the framework and rendered by the renderer the CLI ships. Pages read
 * it and describe nothing themselves, so `dxcl add slate-report` and the page
 * about Slate Report cannot disagree.
 *
 * Like the node catalog, the entries stay English in every language: a
 * translation of them could not be regenerated, so it would drift out of step
 * with the toolkit silently. The chrome around them is translated.
 */
import generated from "./generated/registry.json";

export interface ThemePageEntry {
  id: string;
  title: string;
  summary: string;
  detail: string;
  category: string;
  tags: string[];
  /** Every font the theme asks for, in the order a reader meets them. */
  fonts: string[];
  /** The resolved style — what the install writes and the document carries. */
  style: {
    preset: string;
    page: {
      size: string;
      orientation: string;
      margins: { topMm: number; rightMm: number; bottomMm: number; leftMm: number };
    };
    typography: {
      bodyFont: string;
      headingFont: string;
      bodySizePt: number;
      bodyLineHeight: number;
      color: string;
    };
    palette?: { heading: string; accent: string; muted: string; rule: string; page: string };
    paragraph: { spacingAfterPt: number };
    title: Record<string, unknown>;
    sectionHeading: Record<string, unknown>;
  };
  /** A sample document set in this theme, rendered by the real renderer. */
  previewUrl: string;
}

export interface RegistryDataField {
  path: string;
  type: string;
  summary: string;
}

export interface RegistryFileEntry {
  /** Path inside the package's registry directory. */
  source: string;
  /** Where `dxcl add` puts it, relative to the document project. */
  target: string;
  /** The source itself — what would be copied in, shown rather than described. */
  code: string;
}

export interface ComponentPageEntry {
  id: string;
  title: string;
  summary: string;
  detail: string;
  category: string;
  tags: string[];
  /** The component names the files export. */
  exports: string[];
  /** What it reads, so a reader knows what their data has to carry. */
  dataFields: RegistryDataField[];
  requires: string[];
  /** The theme it was drawn against, where there is one. */
  themeHint: string | null;
  files: RegistryFileEntry[];
  /** The data the preview was built against. */
  previewData: Record<string, unknown>;
  /** What it resolved to: the nodes a renderer or an engine is handed. */
  resolved: Record<string, unknown>[];
  previewUrl: string;
}

export const THEMES = generated.themes as ThemePageEntry[];
export const THEME_CATEGORIES = generated.themeCategories as string[];
export const COMPONENTS = generated.components as ComponentPageEntry[];
export const COMPONENT_CATEGORIES = generated.componentCategories as string[];

/**
 * Throws rather than returning undefined: a page naming something that left the
 * registry is a broken page, and it should fail the build rather than render
 * empty.
 */
export function themeEntry(id: string): ThemePageEntry {
  const found = THEMES.find((theme) => theme.id === id);

  if (!found) {
    throw new Error(
      `Unknown theme "${id}". Known: ${THEMES.map((theme) => theme.id).join(", ")}.`,
    );
  }

  return found;
}

export function componentEntry(id: string): ComponentPageEntry {
  const found = COMPONENTS.find((component) => component.id === id);

  if (!found) {
    throw new Error(
      `Unknown component "${id}". Known: ${COMPONENTS.map((entry) => entry.id).join(", ")}.`,
    );
  }

  return found;
}

/** Where a theme or component lives, canonically. Pass through `localizePath`. */
export function themeHref(id: string): string {
  return `/themes/${id}/`;
}

export function componentHref(id: string): string {
  return `/components/${id}/`;
}

/** The catalog grouped for a browse page, empty groups dropped. */
export function componentsByCategory(): { category: string; components: ComponentPageEntry[] }[] {
  return COMPONENT_CATEGORIES
    .map((category) => ({
      category,
      components: COMPONENTS.filter((component) => component.category === category),
    }))
    .filter((group) => group.components.length > 0);
}

export function themesByCategory(): { category: string; themes: ThemePageEntry[] }[] {
  return THEME_CATEGORIES
    .map((category) => ({
      category,
      themes: THEMES.filter((theme) => theme.category === category),
    }))
    .filter((group) => group.themes.length > 0);
}

/** The command that installs one, printed on every card and page. */
export function addCommand(id: string): string {
  return `npx dxcl add ${id}`;
}
