/**
 * Everything you write a document with: the elements, the hooks, and
 * {@linkcode template} to name the tree.
 *
 * This is the entrypoint a document project imports. Nothing here renders —
 * evaluating JSX records elements, and a build calls the components later.
 *
 * @example Composing a document
 * ```tsx
 * import {
 *   Document,
 *   Paragraph,
 *   Section,
 *   template,
 *   useState,
 * } from "@docxcelerate/docxcelerate/template";
 *
 * const Greeting: Paragraph = () => {
 *   const [name] = useState((data: { name: string }) => data.name);
 *   return <Paragraph id="greeting">Dear {name},</Paragraph>;
 * };
 *
 * export const documentTemplate = template<{ name: string }>(
 *   <Document id="welcome" title="Welcome">
 *     <Section id="opening" title="Opening">
 *       <Greeting />
 *     </Section>
 *   </Document>,
 * );
 * ```
 *
 * @module
 */

import type { DocumentTemplate } from "./components.ts";
import { hostKindOf, isTemplateElement, type TemplateElement } from "./template/element.ts";
import type { DocumentProps } from "./template/elements.ts";

export * from "./template/element.ts";
export * from "./template/elements.ts";
export * from "./template/hooks.ts";
export { deriver, type DeriverModule } from "./runtime/deriver_module.ts";
export { type AiConfig, useAi } from "./template/ai.ts";
export {
  and,
  branch,
  compare,
  ctxPath,
  dataPath,
  derivedPath,
  literal,
  or,
  refValue,
  truthy,
} from "./template/branch.ts";
export type { BranchMode, DeriverMode, DynamicMode } from "./template/context.ts";
export { createPublishData, expr, isPublishValue, publishRefOf } from "./template/publish.ts";
// The helpers compiled control flow calls into. Exported because the transform
// emits imports of them, not because anybody writes one.
export { __and, __compare, __not, __or, __test } from "./template/compiled.ts";
export type { CompiledTest } from "./template/compiled.ts";
export type { ComponentRuntimeOptions, DocumentTemplate } from "./components.ts";
export { buildDocument } from "./components.ts";

/**
 * Names a document tree so a project can point at it.
 *
 * Nothing here is rendered. Evaluating the JSX only builds elements, and the
 * root's id and title are plain props, so a template can be read for what it is
 * called long before anybody has data to build it with.
 *
 * @typeParam TData The shape the template reads.
 * @param element A single `<Document>` element.
 * @returns The template, ready for a project to build.
 * @throws If the element is not a `<Document>`, or is missing an id or title.
 */
export function template<TData>(element: unknown): DocumentTemplate<TData> {
  if (!isTemplateElement(element) || hostKindOf(element.type) !== "document") {
    throw new Error(
      "A template is a single <Document> element. " +
        `Received ${describe(element)}.`,
    );
  }

  const props = element.props as unknown as DocumentProps;

  if (!props.title) {
    throw new Error(
      "<Document> needs a title. It is what the document is called, and the id is taken " +
        "from it when none is written.",
    );
  }

  return {
    schemaVersion: "docxcelerate.template/v0",
    id: props.id ?? documentId(props.title),
    title: props.title,
    metadata: props.metadata,
    element: element as TemplateElement<"document">,
  };
}

/**
 * The name a document takes when nobody wrote one.
 *
 * The title already says what the document is, so repeating it as an id is
 * work with nothing to show for it. A document that is generated by name will
 * want its own, and can say so.
 */
function documentId(title: string): string {
  return title
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "document";
}

function describe(value: unknown): string {
  if (isTemplateElement(value)) {
    const kind = hostKindOf(value.type) ?? value.kind;
    return kind === "component"
      ? "a component — call it from inside <Document>, or return <Document> from it"
      : `a <${kind}> element`;
  }

  return value === null ? "null" : typeof value;
}
